name: SmartInvs
version: 2.0.0-alpha.3
description: Inventory API for your Bukkit Plugins.
author: Rexchoppers, MinusKube
website: https://github.com/rexchoppers/SmartInvs
main: fr.minuskube.inv.SmartInvsPlugin